---
###############################################################################
# Enable Hardware Virtualization
###############################################################################
# Hardware virtualization is automatically enabled based on CPU type.
#
# Reference:
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#enable-hardware-virtualization-iommu

- name: 'virtualization | enable virtual file IO on boot'
  ansible.builtin.copy:
    src:   'etc/modules-load.d/vfio.conf'
    dest:  '/etc/modules-load.d/vfio.conf'
    owner: 'root'
    group: 'root'
    mode:  0644
    force: true

- name: 'virtualization | determine processor type'
  ansible.builtin.shell: 'set -o pipefail && grep -m 1 vendor_id /proc/cpuinfo | cut -d : -f 2 | xargs'
  args:
    executable: '/bin/bash'
  register: _pve_processor
  changed_when: false

# AMD: AuthenticAMD; IOMMU, SVM must be enabled in BIOS
# Intal: GenuineIntel; IOMMU, VT-d must be enabled in BIOS
- name: 'virtualization | determine grub line from processor'
  ansible.builtin.set_fact:
    pve_hardware_virt_grub: "{% if _pve_processor.stdout == 'AuthenticAMD' %}amd_immou{% else %}intel_iommu{% endif %}"

- name: 'virtualization | configure grub for hardware virutalization'
  ansible.builtin.template:
    src:      'grub.j2'
    dest:     '/etc/default/grub'
    owner:    'root'
    group:    'root'
    mode:     0644
    force:    true
    backup:   true
    validate: 'grub-script-check %s'
  notify:
    - 'update grub'
    - 'reboot pve'
