---
###############################################################################
# Configure Cluster DNS
###############################################################################
# Manage cluster DNS.
#
# Args:
#   pve_dns: string /etc/network/interfaces configuration or '' to disable
#       management.
#
# Reference:
# * https://mangolassi.it/topic/21764/configuring-network-settings-for-proxmox-installs/2
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#setup-networking


- name: 'global task | configure cluster DNS'
  block:
    - name: 'global task | check cluster DNS'
      ansible.builtin.template:
        src:   'resolv.conf.j2'
        dest:  '/etc/resolv.conf'
        owner: 'root'
        group: 'root'
        mode:  0644
        force: true
      check_mode: true
      register: _pve_dns_check

    - name: 'global tasks | set cluster DNS' # noqa no-handler conditional
      ansible.builtin.template:
        src:   'resolv.conf.j2'
        dest:  '/etc/resolv.conf'
        owner: 'root'
        group: 'root'
        mode:  0644
        force: true
      when: _pve_dns_check.changed
      notify: 'reboot pve'

    - name: 'global task | restarting node (may take a while)'
      ansible.builtin.debug:
        msg: |
          Cluster node WILL BE restarted to apply DNS changes.

          This will take a few minutes.
      when: _pve_dns_check.changed

  when: pve_dns|length > 0