---
###############################################################################
# LXC/KVM Instance Firewall Configuration (Global)
###############################################################################
# Set a per lxc/kvm firewall.
#
# Both types use the same format and are applied at the datacenter level.
# Firewall files do not exist unless settings are explicitly set. Automatically
# generate a file with default settings to ensure consistency across following
# runs. Initial run will create a firewall definition for each container.
#
# pve-firewall service does not need to be restarted; it will automatically
# apply changes on file change.
#
# /etc/pve uses pmxcfs (a database mounted via fuse). It's POSIX like, but does
# not support specific operations. This causes:
# * Temp files from ansible to fail as it crosses filesystem boundaries
#   (ansible creates a temp file then attempts an atomic move; fails across
#    filesystems).
# * Permissions are auto-applied based on path; no need to set user/group/perms
#   on files in /etc/pve.
# * A Quorate MUST exist to enable writes (auto sync'ed to rest of cluster).
#
# Args:
#   _pve_vm: dict parsed pve_{kvm,lxc} raw yaml values.
#
# Reference:
# * https://pve.proxmox.com/pve-docs/chapter-pve-firewall.html#pve_firewall_vm_container_configuration
# * https://pve.proxmox.com/pve-docs/chapter-pmxcfs.html
# * https://forum.proxmox.com/threads/unable-to-modify-anything-under-etc-pve.10284/
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#firewall
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#ports

- name: '{{ _pve_vm.vmid }} | check for firewall changes' # noqa risky-file-permissions pmxcfs managed
  ansible.builtin.template:
    src:   'vmid.fw.j2'
    dest:  '/etc/pve/firewall/{{ _pve_vm.vmid }}.fw'
    force: true
  check_mode: true
  register: _pve_vm_firewall_check

- name: '{{ _pve_vm.vmid }} | stage firewall changes' # noqa no-handler conditional
  ansible.builtin.template:
    src:   'vmid.fw.j2'
    dest:  '/tmp/{{ _pve_vm.vmid }}.fw'
    owner: 'root'
    group: 'www-data'
    mode:  0640
    force: true
  when: _pve_vm_firewall_check.changed

- name: '{{ _pve_vm.vmid }} | apply firewall changes to pmxcfs' # noqa no-handler execute immediately
  ansible.builtin.command: 'mv /tmp/{{ _pve_vm.vmid }}.fw /etc/pve/firewall/{{ _pve_vm.vmid }}.fw'
  when: _pve_vm_firewall_check.changed