---
###############################################################################
# Configure Cluster Network
###############################################################################
# PVE uses interfaces.new and applies changes on reboot, removing the file.
# Using a template will always trigger a copy if system has been rebooted or
# does not have pending network changes. Manually calculate 'interfaces'
# checksum and compare to trigger network changes.
#
# Args:
#   pve_interfaces: string /etc/network/interfaces configuration or '' to
#       disable management.
#
# Reference:
# * https://r-pufky.github.io/docs/virtualization/hypervisors/pve/index.html#setup-networking
# * https://pve.proxmox.com/wiki/Network_Configuration
# * https://pve.proxmox.com/pve-docs/pve-admin-guide.html#sysadmin_network_configuration

- name: 'global task | configure cluster network'
  block:
    - name: 'global task | check cluster network'
      ansible.builtin.template:
        src:   'interfaces.j2'
        dest:  '/etc/network/interfaces'
        owner: 'root'
        group: 'root'
        mode:  0644
        force: true
      check_mode: true
      register: _pve_network_check

    - name: 'global task | set cluster network' # noqa no-handler conditional
      ansible.builtin.template:
        src:   'interfaces.j2'
        dest:  '/etc/network/interfaces.new'
        owner: 'root'
        group: 'root'
        mode:  0644
        force: true
      when: _pve_network_check.changed
      notify: 'reboot pve'

    - name: 'global task | restarting node (may take a while)'
      ansible.builtin.debug:
        msg: |
          Cluster node WILL BE restarted to apply network changes.

          This will take a few minutes.
      when: _pve_network_check.changed

  when: pve_interfaces|length > 0