---
###############################################################################
# Create ISO Image on Cluster Node
###############################################################################
# Downloads a specified ISO to a given cluster node if needed. This occurs when
# a template is provided, but cloud_init is false.
#
# Args:
#   _pve_vm: dict kvm_config parse options.
#   pve_vm_iso_location: string location of ISO images on cluster.
#   pve_vm_download_timeout: integer seconds before aborting download.
#
# Reference:
# * https://pve.proxmox.com/pve-docs/pvesh.1.html
# * https://pve.proxmox.com/pve-docs/pve-admin-guide.html

- name: '{{ _pve_vm.vmid }} iso | processing iso'
  ansible.builtin.set_fact:
    _pve_iso_exists: false

- name: '{{ _pve_vm.vmid }} iso | list cluster/node isos'
  ansible.builtin.command: 'pvesh get /nodes/{{ _pve_vm.node.split(".")[0] }}/storage/local/content --output-format json'
  register: _pve_iso_list
  changed_when: false
  delegate_to: '{{ _pve_vm.node }}'

- name: '{{ _pve_vm.vmid }} iso | check if required iso exists on cluster/node'
  ansible.builtin.set_fact:
    _pve_iso_exists: true
  when: _pve_vm.template.name == node_iso.volid.split('local:iso/')[-1]
  loop: '{{ _pve_iso_list.stdout|from_json }}'
  loop_control:
    loop_var: node_iso

- name: '{{ _pve_vm.vmid }} iso | downloading (timeout after {{ pve_vm_download_timeout }} seconds)'
  ansible.builtin.debug:
    msg: |
      Downloading: {{ _pve_vm.template.file }}
  when: not _pve_iso_exists

- name: '{{ _pve_vm.vmid }} iso | cluster {{ _pve_vm.node }} downloading: {{ _pve_vm.template.file }}'
  ansible.builtin.get_url:
    url:      '{{ _pve_vm.template.url }}'
    dest:     '{{ pve_vm_iso_location }}/{{ _pve_vm.template.file }}'
    checksum: '{{ _pve_vm.template.algorithm }}:{{ _pve_vm.template.checksum }}'
    timeout:  '{{ pve_vm_download_timeout }}'
    owner:    'root'
    group:    'root'
    mode:     0644
  delegate_to: '{{ _pve_vm.node }}'
  when: not _pve_iso_exists

- ansible.builtin.import_tasks: roles/pve/kvm/tasks/operations/rescan.yml
